api/urls.py
from django.urls import path
from .views import get_requests, post_requests

app_name = 'api'
urlpatterns = [
    path('v1/get/', get_requests, name='get_request'),   # GET API
    path('v1/post/', post_requests, name='post_request')   # POST API
]

dj_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('rest/', include('rest.urls')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
]

rest/urls.py
from django.urls import path
from . import views

app_name = 'rest'
urlpatterns = [
    path('', views.RestEndpoint.as_view(), name='rest_endpoint'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:title" content="Test API" />
    <meta property="og:type" content="website" />

    <title>Test API</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    {% block extrahead %}
    {% endblock extrahead %}
</head>

<body>
<div class="container py-3">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center mb-3">Test API</h2>
            <div class="form-group" style="text-align: center;">
                <button class="btn btn-primary" onclick="window.open('{% url 'api:get_request' %}', '_self')">GET (Filter requests by IP)</button>
                <button class="btn btn-primary" onclick="window.open('{% url 'api:post_request' %}', '_self')">POST (Validate Data)</button>
                <button class="btn btn-primary" onclick="window.open('{% url 'home' %}', '_self')">Go Home</button>
            </div>
            <hr class="mb-4">
{% block content %}
{% endblock %}
        </div>
    </div>
</div>

<!-- jQuery and Bootstrap core JS, plus Popper -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

<script>
$( document ).ready(function() {
    $([document.documentElement, document.body]).animate({
        scrollTop: $("#responseArea").offset().top
    }, 2000);
});
</script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link href='https://fonts.googleapis.com/css?family=Exo:400,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <style>
        html, body{
            height: 100%;
        }

        body {
			background-image: url(https://i.imgur.com/qZ15Eu8.jpg) ;
			background-position: center center;
			background-repeat:  no-repeat;
			background-attachment: fixed;
			background-size:  cover;
			background-color: #999;
        }

        div, body{
            margin: 0;
            padding: 0;
            font-family: exo, sans-serif;
        }

        .wrapper {
            height: 100%;
            width: 100%;
        }

        .box {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 20rem;
            padding: 2.5rem;
            box-sizing: border-box;
            background: rgba(0, 0, 0, 0.5);
            border-radius: 0.625rem;
        }

        .box h2 {
            margin: 0 0 2rem;
            padding: 0;
            color: #fff;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="wrapper">
    <div class="box">
        <h2>Choose your side</h2>
         <div class="form-group" style="text-align: center;">
            <button class="btn btn-primary" style="margin-bottom: 10px;" onclick="window.open('{% url 'api:post_request' %}', '_self')">Custom API Views</button>
            <button class="btn btn-primary" style="margin-bottom: 10px;" onclick="window.open('{% url 'rest:rest_endpoint' %}', '_self')">REST API Views</button>
         </div>
    </div>
</div>
</body>
</html>

templates/my_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block extrahead %}
<style>
#div_id_first_name label, #div_id_last_name label,
#div_id_email label, #div_id_password label {
    display: none;
}

#div_id_first_name, #div_id_last_name,
#div_id_email, #div_id_password {
    margin-bottom: inherit;
}

.response {
    font-size: 12px;
    height: auto;
    font-family: "Consolas", sans-serif;
}

#responseArea {
    background-color: #fff;
}
</style>
{% endblock extrahead %}

{% block content %}
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="card card-outline-secondary">
                        <div class="card-header">
                            <h3 class="mb-0" style="text-align: center;">Response</h3>
                        </div>

                        <div class="card-body">
                            <div class="row mb-1">
                                <div class="col-lg-12">
                                    <div class="form-control response">
                                        <span>
                                            <b>{{ status }}</b><br>
                                        </span>

                                        <textarea id="responseArea" class="form-control response" style="color: #D14; border: none;" rows="{% if form %}10{% else %}15{% endif %}" readonly>{{ json_response }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% if form %}
            <br><br>
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="card card-outline-secondary">
                        <div class="card-header">
                            <h3 class="mb-0" style="text-align: center;">HTML Form</h3>
                        </div>

                        <div class="card-body">
                            <form action="{% url 'api:post_request' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">First name</label>
                                    <div class="col-lg-9">
                                        {{ form.first_name|as_crispy_field }}
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Last name</label>
                                    <div class="col-lg-9">
                                        {{ form.last_name|as_crispy_field }}
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Email</label>
                                    <div class="col-lg-9">
                                        {{ form.email|as_crispy_field }}
                                    </div>
                                </div>


                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Password</label>
                                    <div class="col-lg-9">
                                        {{ form.password|as_crispy_field }}
                                    </div>
                                </div>


                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label"></label>
                                    <div class="col-lg-9">
                                        <input class="btn btn-primary" type="submit" value="POST">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endif%}
{% endblock %}